function Clear() {
	document.getElementById('MSRP').value = "";
	document.getElementById('MilesPerYear').value = "";
	document.getElementById('DownPaymentPercent1').value = "";
	document.getElementById('Months1').value = "";
	document.getElementById('Interest1').value = "";
	document.getElementById('Incentives1').value = "";
	document.getElementById('DownPaymentPercent2').value = "";
	document.getElementById('Months2').value = "";
	document.getElementById('Interest2').value = "";
	document.getElementById('Incentives2').value = "";
	document.getElementById('DownPaymentPercent3').value = "";
	document.getElementById('MonthlyPayment3').value = "";
	document.getElementById('Months3').value = "";
	document.getElementById('Overage').value = "";
	document.getElementById('MilesIncluded').value = "";
	document.getElementById('Out1').innerHTML = "";
	document.getElementById('Out2').innerHTML = "";
	document.getElementById('Out3').innerHTML = "";
}